version: '3.7'
services:
  app:
    container_name: app-router
    image: iazadur/app-router:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    env_file:
      - .env